apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-jn8m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-jn8m
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: devfile-sample-go-basic-jn8m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-jn8m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-jn8m
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mreid1-tenant/devfile-sample-go-basic/devfile-sample-go-basic-jn8m@sha256:a18c0f7e6ac1f93355a1e3ba5a5c17b71e07d8e3ab73b5b67dd46e536b380306
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
